#!/bin/sh

FILE=`git diff --staged --name-only --diff-filter=AM | grep -E '*.php$'`

echo "$FILE"

FIXED=`./vendor/bin/sail exec -T web ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --path-mode=intersection $FILE`

echo "$FIXED"

# 整形されたファイルがあった場合、addする
if [[ $FIXED =~ '1)' ]]
then
    echo 'ファイルが自動整形されました。コミットを中断します。自動整形されたファイルを確認してください。'
    git add .
    exit 1
else
    echo 'Nothing fixed file. Commited!'
fi
